"""empty message

Revision ID: d7f8a9a3ca82
Revises: 9fde9b61d6d8
Create Date: 2021-05-13 10:05:37.205007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f8a9a3ca82'
down_revision = '9fde9b61d6d8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models2'))
    )
    op.create_index('my_index2', 'models2', ['name'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index2', table_name='models2')
    op.drop_table('models2')
    # ### end Alembic commands ###
