"""adding monitoring_contact to node_group

Revision ID: b63d86dd6535
Revises: 3ee80746cca8
Create Date: 2023-03-22 10:53:01.647779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63d86dd6535'
down_revision = '3ee80746cca8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_groups', sa.Column('monitoring_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_groups', 'monitoring_contact')
    # ### end Alembic commands ###
