"""Adding received and inservice dates to physical_devices

Revision ID: d8e2cee1e054
Revises: 277a0c334975
Create Date: 2024-08-01 08:20:29.759054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e2cee1e054'
down_revision = '277a0c334975'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_devices', sa.Column('received_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('physical_devices', sa.Column('inservice_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physical_devices', 'inservice_date')
    op.drop_column('physical_devices', 'received_date')
    # ### end Alembic commands ###
