"""Adding technical_contact

Revision ID: 277a0c334975
Revises: b63d86dd6535
Create Date: 2024-05-14 09:58:10.063312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277a0c334975'
down_revision = 'b63d86dd6535'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_groups', sa.Column('technical_contact', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_groups', 'technical_contact')
    # ### end Alembic commands ###
